---
title: "My CV"
author: "Alexandre Camargo Martensen"
date: "February 26, 2016"
output: 
  html_document:
    keep_md: true
---

<h3><center>Alexandre Camargo Martensen</center></h3>

Contact information:<br>
**Email:** martensen *at* terra.com.br, acmartensen *at* gmail.com, martensen *at* ufscar.br <br>
**Phone:**  +55 15 9 9700 9601 + 55 15 3256-9026

___

<h3>Education</h3>

2012-2017 ; **Ph.D.** Ecology and Evolutionary Biology, University of Toronto, Department of Ecology and Evolutionary Biology 
<p>  Advisor: Marie-Josee Fortin

2005-2008     **M.Sc.** University of São Paulo, Department of Ecology
<p>  Advisor: Jean Paul Metzger
          
1997-2001 	  **B.Sc.** Biological Science, University of São Paulo,	Bioscience Institute

2000-2001 	  Teacher diploma,	University of São Paulo,	Bioscience Institute.

<br>
<h3>Publications</h3>

**2018** <p>


Giubbina, M.F., MARTENSEN, A.C., Ribeiro, M.C. 2018. Sugarcane and Eucalyptus plantation equally limit the movement of two forest-dependent understory bird species. Austral Ecology - DOI10.1111/aec.12589 



Hasui, É., J. P. Metzger, R. G. Pimentel, L. F. Silveira, A. A. d. A. Bovo, A. C. MARTENSEN, A. Uezu, A. L. Regolin, A. Â. Bispo de Oliveira, C. A. F. R. Gatto, C. Duca, C. B. Andretti, C. Banks-Leite, D. Luz, D. Mariz, E. R. Alexandrino, F. M. de Barros, F. Martello, I. M. d. S. Pereira, J. N. da Silva, K. M. P. M. d. B. Ferraz, L. N. Naka, L. dos Anjos, M. A. Efe, M. A. Pizo, M. Pichorim, M. S. S. Gonçalves, P. H. C. Cordeiro, R. A. Dias, R. d. L. Muylaert, R. C. Rodrigues, T. V. V. da Costa, V. Cavarzere, V. R. Tonetti, W. R. Silva, C. N. Jenkins, M. Galetti, and M. C. Ribeiro. 2018. ATLANTIC BIRDS: a data set of bird species from the Brazilian Atlantic Forest. Ecology V. 99, p. 497. DOI: 10.1002/ecy.2119


**2017** <p>


Lima, F., G. Beca, R. L. Muylaert, C. N. Jenkins, M. L. L. Perilli, A. M. O. Paschoal, R. L. Massara, A. P. Paglia, A. G. Chiarello, M. E. Graipel, J. J. Cherem, A. L. Regolin, L. G. R. Oliveira Santos, C. R. Brocardo, A. Paviolo, M. S. Di Bitetti, L. M. Scoss, F. L. Rocha, R. Fusco-Costa, C. A. Rosa, M. X. Da Silva, L. Hufnagell, P. M. Santos, G. T. Duarte, L. N. Guimarães, L. L. Bailey, F. H. G. Rodrigues, H. M. Cunha, F. M. Fantacini, G. O. Batista, J. A. Bogoni, M. A. Tortato, M. R. Luiz, N. Peroni, P. V. De Castilho, T. B. Maccarini, V. P. Filho, C. D. Angelo, P. Cruz, V. Quiroga, M. E. Iezzi, D. Varela, S. M. C. Cavalcanti, A. C. MARTENSEN, E. V. Maggiorini, F. F. Keesen, A. V. Nunes, G. M. Lessa, P. Cordeiro-Estrela, M. G. Beltrão, A. C. F. De Albuquerque, B. Ingberman, C. R. Cassano, L. C. Junior, M. C. Ribeiro, and M. Galetti. 2017. ATLANTIC-CAMTRAPS: a dataset of medium and large terrestrial mammal communities in the Atlantic Forest of South America. Ecology v. 98, p. 2979. DOI: 10.1002/ecy.1998



MARTENSEN, A. C., S. Saura, and M.-J. Fortin. 2017. Spatio-temporal connectivity: assessing the amount of reachable habitat in dynamic landscapes. Methods in Ecology and Evolution 8:1253-1264. doi: 10.1111/2041-210X.12799 PDF

Braga, A.C.R. & MARTENSEN, A.C. 2017. Smallholders: Drivers or targets of Amazonian deforestation? Human Geography 10(1): 67-69 PDF 

**2015** <p>
Banks-Leite, C.; Pardini, R.; Tambosi, L.R.; Pearse, W.D.; Bueno, A.A.; Bruscagin, R.T.; Condez, T.H.; Dixo, M.; Igari, A.; **MARTENSEN**, A.C., Metzger, J.P. 2015. Response to Comment on "Using ecological thresholds to evaluate the costs and benefits of set-asides in a biodiversity hotspot". Science 347(6223), pp 731.

**2014** <p>
Pütz, S.; Groeneveld, J.; Henle, K.; Knogge, C.; **MARTENSEN**, A.C., Metz, M.; Metzger, J.P.; Ribeiro, M.C.; Paula, M. D. de & Huth, A. 2014. Long-term carbon loss in fragmented Neotropical forests. Nature Communications 5:5037. (2014). DOI:10.1038/ncomms6037 *Journal's Featured Picture of the Week*

*Media coverage*:<br>
International: Science daily, Daily News en , Eurekalert , azocleantech , Nature World News , Planet Experts, DAAD Vbio (german), TV 21 (german), Ad Hoc News (german), Scinexx (german), Innovations report (german)<br>
Brazilian: Jornal Estado de São Paulo, Jornal Folha de São Paulo, Portal UNESP, Madeira Total, Fundacao Getulio Vargas, O Eco

Banks-Leite, C.; Pardini, R.; Tambosi, L.R.; Pearse, W.D.; Bueno, A.A.; Bruscagin, R.T.; Condez, T.H.; Dixo, M.; Igari, A.; **MARTENSEN**, A.C., Metzger, J.P. 2014. Using ecological thresholds to cost set-asides in a biodiversity hotspot. Science 345, no. 6200, pp: 1041-1045. DOI:10.1126/science.1255768

*Media coverage:*<br>
International: Science Magazine News, Mongabay, Conservation magazine, Science Daily, Science News line, Phys.org<br>
Brazilian: Reporter Eco (TV), Jornal Estado de São Paulo, Jornal Folha de São Paulo, Eco Debate, SOS Mata Atlântica, Frente Parlamentar Ambientalista, Revista Fapesp, UOL

Banks-Leite, C.; Pardini, R.; Tambosi, L.R.; Pearse, W.D.; Bueno, A.A.; Bruscagin, R.T.; Condez, T.H.; Dixo, M.; Igari, A.; **MARTENSEN**, A.C., Metzger, J.P. 2014. Conserving Brazil's Atlantic forests-response. Science 346(6214), pp 1193.

Tambosi, L.R.; **MARTENSEN**, A.C. ; Ribeiro, M.C.; Metzger, J.P. 2014. A framework to optimize biodiversity restoration efforts based on habitat amount and landscape connectivity. Restoration Ecology (22)2: 169-177 169

**2013** <p>
Gama, V.F.; **MARTENSEN**, A.C.; Ponzoni, F.J., Hirota, M.M.; Ribeiro, M.C. 2013. Site Selection for restoration planning: A protocol with landscape and legislation based alternatives. Natureza e Conservação 11(2): 1-12. DOI:10.4322/natcon.2013.025

Ribeiro, M.C.; Páglia, A.; **MARTENSEN**, A.C.; Cunha, A.A.; Borges, B.D.; Belchior, C.; Guedes, F.; Prem, I.; Metzger, J.P.; Ribeiro, J.W.; Galetti, M.; Bernardo, R.; Salmona, Y. 2013. Estratégias para a conservação da biodiversidade na Mata Atlântica incorporando múltiplas iniciativas e escalas. Pp: 137-165.

Tambosi, L.R.; **MARTENSEN**, A.C. ; Ribeiro, M.C.; Metzger, J.P.. 2013. Identificação de áreas para o aumento da conectividade dos remanescentes e unidades de conservação da Mata Atlântica. Capítulo II. Mapeamentos para a Conservação e Recuperação da Biodiversidade na Mata Atlântica Brasileira. Pp 33-85. PDF

**2012** <p>
**MARTENSEN**, A.C.; Ribeiro, M.C.; Banks-Leite, C.; Prado, P.I.; Metzger, J.P. 2012. Associations of Forest Cover, Fragment Area, and Connectivity with Neotropical Understory Bird Species Richness and Abundance. Conservation Biology, 26(6): 1100-1111. DOI:10.1111/j.1523-1739.2012.01940.x

**2011** <p>
Banks-Leite, C; Ewers, R.M.; Kapos, V.; **MARTENSEN**, A.C. ; Metzger, J.P. 2011. Comparing species and measures of landscape structure as indicators of conservation importance. Journal of Applied Ecology v. 48, p. 706-714. DOI:10.1111/j.1365-2664.2011.01966.x

Boscolo, D. & **MARTENSEN**, A.C. 2011. Alterações no Código Florestal afetam todos os brasileiros. Ciência Hoje, v. 48, p. 74-75. *This article was used as an educational tool in high schools by the Secretary of Education from Rio the Janeiro*

Ribeiro, M.C.; **MARTENSEN**, A.C.; Metzger, J.P.; Scarano, F.; Fortin, M.J. 2011. The Brazilian Atlantic Forest: A Shrinking Biodiversity Hotspot. In: Frank E. Zachos; Jan Christian Habel. (Org.). Biodiversity Hotspots: Distribution and Protection of Conservation Priority Areas. Biodiversity Hotspots: Distribution and Protection of Conservation Priority Areas. Berlin: Springer-Verlag, p. 405-434.

**2010** <p>
Metzger, J.P.; Ribeiro, M.C.; **MARTENSEN**, A.C. 2010. Paisagens Atlânticas Brasileiras. In: Marone, E.; Riet, D.; Melo, T. (Org.) Brasil Atlântico: um País com a Raiz na Mata. Brasil Atlântico: um País com a Raiz na Mata. Rio de Janeiro: Mar de Idéias/IBIO, p. 130-163.

**2009** <p>
Ribeiro, M.C.; Metzger, J.P.; **MARTENSEN**, A.C.; Ponzoni, F.J.; Hirota, M.M. 2009. The Brazilian Atlantic Forest: How much is left, and how is the remaining forest distributed? Implications for conservation. Biological Conservation, v. 142, p. 1141-1153. doi:10.1016/j.biocon.2009.02.021

*Media coverage*: Jornal Folha de São Paulo, Eco Debate, O Eco, Amazonarium, OPA

Metzger, J.P.; **MARTENSEN**, A.C.; Dixo, M.; Bernacci, L.C.; Ribeiro, M.C.; Teixeira, A.M.G.; Pardini, R. 2009. Time-lag in biological responses to landscape changes in a highly dynamic Atlantic forest region. Biological Conservation, v. 142, p. 1166-1177. DOI:10.1016/j.biocon.2009.01.033

**2008** <p>
**MARTENSEN**, A.C.; Pimentel, R.G.; Metzger, J.P. 2008. Relative effects of fragment size and connectivity on bird community in the Atlantic Rain Forest: Implications for conservation. Biological Conservation, v. 141, p. 2184-2192. DOI:10.1016/j.biocon.2008.06.008

**MARTENSEN**, A.C.2008. Conservação de aves de sub-bosque em paisagens fragmentadas: Importância da cobertura e da configuração do hábitat. Master's Dissertation, Instituto de Biociências, University of São Paulo, São Paulo.<a href="http://www.teses.usp.br/teses/disponiveis/41/41134/tde-26092008-133514/publico/Martensen.pdf">PDF</a>

**2007** <p>
Metzger, J.P.; Fonseca, M.; Oliveira-Filho, F.; **MARTENSEN**, A.C. 2007. O uso de modelos em Ecologia de Paisagens. Megadiversidade, v. 3, p. 64-73.

**2006** <p>
Develey, P.F.; **MARTENSEN**, A.C. 2006. Birds of Morro Grande Reserve. Biota Neotropica (Ed. Portuguesa), v. 06(2)
<a href="http://www.scielo.br/pdf/bn/v6n2/v6n2a07.pdf">PDF</a>

Metzger, J.P.; Alves, L.; Pardini, R.; Dixo, M.O.; Nogueira, A.; Negrão, M.; **MARTENSEN**, A.C.; Catharino, L. 2006. Características ecológicas e implicações para a conservação da Reserva Florestal do Morro Grande. BiotaNeotropica, v. 06 (2), p. 01-13.
<a href="http://www.biotaneotropica.org.br/v6n2/pt/abstract?article+bn01006022006">PDF</a> ISSN 1676-0603

<br>
<h3>Teaching experience</h3>

2016           - Applied Conservation Biology, Undergraduate Teaching Assistant, University of Toronto <p>
2015           - Topics for Biodiversity Conservation, Undergraduate Teaching Assistant, University of Toronto <p>
2013-2014      - Biostatistics, Undergraduate Teaching Assistant, University of Toronto <p>
2012           - Community Ecology, Teaching Fellow, University of the State of São Paulo (Rio Claro) <p>
2009 - Present - Applied Landscape Ecology (1 week course, twice a year), Institute of Ecological Research (IPE) <p>
2008           - Agroecology, technical course of family agriculture, Centro Paula Souza <p>
2011           - Landscape Ecology to the Eletric sector (EPE, Brazilian FEderal Government) <p>
2011           - Applied Landscape Ecology, Ibio <p>
2010           - Landscape Ecology to the Eletric sector (EPE, Brazilian FEderal Government) <p>
2006           - Landscape Ecology (1 week course, Semana Temática - Workshop), University of the State of São Paulo (Rio Preto) <p>
2005           - Landscape Ecology (1 week course, Semana Temática - Workshop), Floresta Viva, University of the State of São Paulo (Botucatu)<p>
2004-2005      - Bird biodiversity (2 days course), Institute of Ecological Research (IPE)<p>
2004-2005      - Landscape Ecology (5 days course), Institute of Ecological Research (IPE)<p>
2000-2007      - Teacher and coordinator of outdoor activities for schools of São Paulo, Campinas and Rio de Janeiro, with field trips to different places such as: Pantanal, Cerrado and Atlantic Forest<p>
2001           - Trainee at the public high school of the municipality of Carapicuíba (SP) <p>
2001           - Animal Ecology, Undergraduate Teaching Assistant, University of São Paulo<p>
1998           - Fauna, Flora and the Environment, Undergraduate Teaching Assistant, University of São Paulo<p>
1997-2005      - Private classes to high school student (Biology and Science)<p>

<br>
<h3>Grants and Funding</h3>

- Connaught International Scholarships for Doctoral Students (2012-2016, CAD$150,000)

- Masters Scholarship (FAPESP, 04/11279-7, 2005-2006) - Understory bird conservation in fragmented landscapes: The importance of land cover and configuration (R$ 13,000) 

- Desenvolvimento Tecnológico e Industrial (CNPq)

- Scholarship Alemanha (2005)

- IALE 2003 - Darwin, Australia (EUR$ 1000.00)

- Undergraduate research scholarship (FAPESP - 00/08046-0) - Variation in the abundance and richness of understory birds in a fragmented landscape 

<br>
<h3>Awards</h3>

2011 - Most Cited Author - Biological Conservation (2008-2011), Elsvier

2011 - Higly Cited Author - Biological Conservation (2008-2011), Elsvier

2011 - Higly Cited Author - Biological Conservation (2008-2011), Elsvier

2010 - Most Cited Author - Biological Conservation (2007-2010), Elsvier

2010 - Higly Cited Author - Biological Conservation (2007-2010), Elsvier

<h3>Selected international presentations</h3>
2012 - 49th Annual Meeting of the Association of Tropical Biology and Conservation - "Methodological framework to optimize restoration efforts based on landscape connectivity and resilience" - Oral presentation<p>
2009 - I Latin America International Association of Landscape Ecology - Atlantic Forest Conservation - Oral presentation<p>
2009 - I Latin America International Association of Landscape Ecology - Effects of habitat loss and fragmentation on birds - Oral presentation<p>
2005 -  XIX Annual meeting of the Society for Conservation Biology - "Conservation of understory birds in the SE Atlantic rainforest, Brazil: corridor and fragment size effects" - Oral presentation<p>
2003 - 7th Neotropical Ornithological Congress - "Bird species richness in tropical forest fragments with different sizes and connectivity" - Oral presentation (sponsor by FAPESP)<p>
2003 - 6th International Association for Landscape Ecology World Congress - "Conservation of understory birds in the SE Atlantic Rain Forest, Brazil" - sponsor by the Conference<p>
2003 - 18th Annual Symposium of the International Association for Landscape Ecology - US Chapter - Impacts of forest deforestation and fragmentation on the understory bird community in the Atlantic Rain Forest of Brazil<p>
1998 - 13th Argentine mastzoology journey - "Preliminary results of hair morphology analysis of small mammals from the Brazilian cerrado (Brazilian savanna)"<p>

<h3>Selected recent talks</h3>
2010 - Forest Institute of São Paulo (IF/SMA/SP), Debate sobre as alterações no Código Florestal<p>
2010 - Biota targets (FAPESP), Academia Brasileira de Ciências (ABC), Sociedade Brasileira para o Progresso da Ciência (SBPC) - "Atlantic Forest Conservation"<p> 
2010 - Instituto de Biociências (USP), Debate sobre as alterações no Código Florestal<p>
2010 - Faculdade de Saúde Pública (USP) e PARTICIPARE – Instituto de Meio Ambiente e Cidadania, "Impactos  ambientais  das  alterações  da  lei  do  Código Florestal"<p>
2008 - Faculdade de Tecnologia do Estado de São Paulo, FATEC - "Conservação e Manejo da Mata Atlântica Brasileira: oportunidades para a silvicultura"<p>
2008 - Faculdade de Itapeva, FAIT - "A Mata Atlântica Brasileira, perspectivas para a Conservação"<p> 
2008 - Centro Paula Souza, "As Paisagens da Mata Atlântica"<p>
2007 - Reunião anual do DEPRN, "Modelagens para o Manejo de Paisagens: Perspectivas para a Conservação da Biodiversidade no Estado de São Paulo"<p>
2007 - Workshop "Conservação da Biodiversidade em paisagens fragmentadas: Perspectivas para a conservação" Universidade Federal de Alfenas (UNIFAL) e Universidade de São Paulo (USP)
2007 - III Semana do Meio Ambiente do Exército Brasileiro, "Aves e o espaço aéreo"<p>
2007 - Seminário Internacional de Desenho da Conservação, Palestra "O entorno norte do Continuum de Paranapiacaba, ameaças e perspectivas para a conservação"<p>
2006 - "Ecologia de Paisagens", Congresso Brasileiro de Zoologia<p>
2004 - VIII Congresso Brasileiro de Arborização Urbana - "Corredores biológicos em áreas urbanas"<p> 


<br>
<h3>Academic services</h3> <p>
**Reviewer**: Bird Conservation International, Biodiversity and Conservation, Biological Conservation, Biology Letters, Biota Neotropica, Ecological Indicators, Ecological Applications, Journal of Applied Ecology, Journal of Field Ornithology, Natureza e Conservação, Ecography, PlosOne, Brazilian Journal of Ornithology

<br>
<h3>Other academic experiences</h3>
2005 - Exchange student - Department of Conservation Biology / Centre for Environmental Research, (Leipzig - Germany) (sponsor by CNPq)<p>
2005 - Exchange student - Department of Wildlife Ecology and Wildlife Management / University of Freiburg, (Freiburg - Germany) (sponsor by CNPq)<p>
2003-2004 - Responsible for the technical project: "Impacts of forest fragmentation on bird community in the Atlantic Rainforest: relative importance of fragment size and connectivity" (DTI/CNPq)<p>
2001-2002 - Exchange student - Simulation and ecosystem management Lab, Forestry Department / University of British Columbia, Vancouver, Canada<p>

<br>
<h3>Conference organization</h3>
II Brazilian Conference of Landscape Ecology, Salvador, Bahia, Brazil.

<br>
<h3>Languages</h3>
- Portuguese, native
- English, fluent
- Spanish, basic

<br>
<h3>Professional Experience</h3>

**Director of Taki Ambiental (2007-Present)** Main projects:<p>
- Spatial analysis and sampling design for jaguar monitoring in the Alto Paranapanema river basin (2014-2015) - Concremat<p>
- Forest restoration Guapiara e Almas river basins - SP (2011-2013) - Iniciativa Verde<p>
- Spatial patterns in the Amazonian deforestation frontier (2012 - 2013) - WWF<p>
- Statistical analysis for the monitoring program of the hydroeletric of Jirau (2012) - Arcadis Logos<p>
- Site selection for conservation in the Atlantic Forest (2011-2012) - Brazilian Ministry of the Environmental <p>
- Spatial analysis for environmental impact assessment of the São Luís dos Tapajós hydroelectric project (2011-2012) - WorleyParsons<p>
- Forest spatial dynamics in the south of Bahia (2011-2012) - Ibio<p>
- Coordination of the project for the creation of the Paranapanema water springs state park (PENAP)- SP (2011-2012) - Funbio, Reserva da Biosfera da Mata Atlântica<p>
- Spatial analysis and final report for the environmental impact assessment of the terrestrial ecosystems  of the Doce, Peixes and Piracicaba watersheds (MG) (2010) - Geotechnologies, Vale<p>
- Forest restoration - Permanent Preservation Areas and Legal Reserve of the Fazenda União settlement (Guapiara, SP) (2011-2012), Instituo ECOAR Florestal/Instituto Refloresta - Fehidro<p>
- Site selection for restoration in the Brazilian Atlantic Forest (2011) - Brazilian Environmental Ministry, Funbio<p>
- Spatial analysis for the environmental impact assessment of the Marabá hydroelectric project, Tocantins and Araguaia rivers (2011-2012) - Marabá Energia, CCC<p>
- Statistical analysis for the monitoring program of the hydroelectric project of Jirau (2010-2012) - Arcadis Tetraplan<p>
- Spatial analysis for the socio-ecological evaluation of the Juruena river basin (MT/AM) (2007-2009) - CNEC Engenharia S/A, EPE - Empresa de Pesquisa Energética (Brazilian Federal Government)<p>
- Spatial analysis for the socio-ecological evaluation of the Tibagi river basin (PR) (2008-2009) - CNEC Engenharia S/A, EPE - Empresa de Pesquisa Energética (Brazilian Federal Government)<p>
- Spatial analysis and final report for the environmental impact assessment of the terrestrial ecosystems of the Velhas and Paraopebas watersheds (MG) (2008-2009) - Geotechnologies, Vale<p>
-	Spatial analysis for the environmental impact assessment of the small hydroeletric unit (PCH) São Francisco, Pardo river, SP (2008-2009) - Ampla<p>
-	Spatial analysis for the environmental impact assessment of the small hydroeletric unit (PCH) Ponte Branca, Pardo river, SP (2008-2009) - Ampla<p>
-	Preliminary analysis for supporting the biotic studies of the environmental impact assessment of the hydroeletric project of the Marabá Tocantins and Araguaia river basins (2008-2009) - CNEC Engenharia S/A, CCC<p>
-	Technical assistance capacitation to small holders in Guapiara (SP) (2007-2009) - Guapiara municipality<p>
- Agroecological project coordinator (municipalities of Capão Bonito and Ribeirão Grande, SP) (2007 - 2008), Instituto de Desenvolvimento Ambiental Sustentável, Companhia de Cimento Ribeirão Grande - CCRG <p>

**Secretary of Agriculture, Tourism and the Environment of Guapiara (SP) (2009-2010)** 
The county of Guapiara is one of the last counties in the State of São Paulo that has the majority of the population in the rural area. Moreover, it harbors part of the largest remnant of the Atlantic Forest, therefore, presents great challenges to the sustainable development. <p>
Main activities: <p>
- Implemented a sustainable agricultural practices project (80,000.00 R$/annually)<p>
- Created a database of restoration areas in the county<p>
- Developed an agricultural technical assistance program that served 1300 families (2 agronomic engineers, 1 veterinary, 3 agricultural technicians, 6 tractor operators and 1 tractor team coordinator; budget of around 600,000.00R$/annually)<p>
- Responsible for managing the public agricultural market (20 employees involved, 350 tons of produce/week)<p>
- Developed a Payment of Ecosystem Services project<p>
- Ensured continuity of the projects initiated when the position was Secretary of Agriculture and Supply<p>

**Secretary of Agriculture and Supplies of Guapiara (SP) (2009)** Main activities:<p>

- Managed a dairy project (total amount invested 715,000.00 R$, team: 1 Veterinary, 1 agronomic engineer and 1 agricultural technician)<p>
- Implemented a native bees and agroforest project<p>

<h3>Courses</h3>

2007 - Produção em Sistemas Agroflorestais. (Carga horária: 32h), IPE - Instituto de Pesquisas Ecológicas<p>
2002 - Extensão universitária em Methods & tools to model and predict species distribution - University of Kansas<p>
2002 - Análise de dados de biodiversidade, Programa Biota/Fapesp<p>
2001 - Biologia de serpentes, Sociedade Brasileira de Herpetologia<p>
2000 - Ecologia quantitativa: Introdução ao delineamento experimental e análise de dados, UNESP Rio Claro e UNITAU<p>
2000 - Observação de aves, IB-USP-Semana Temática<p>
2000 - Teoria dos refúgios e a Mata Atlântica, IB-USP-Semana Temática (prof. Aziz Ab'Saber) <p>
2000 - Fundamentos das ciências evolutivas, Fio Cruz<p>
1999 - Técnica de estudo de felinos em vida livre, Congresso Brasileiro de Felinos<p>
1999 - EIA-RIMA, IB-USP-Semana Temática<p>
1998 - Extensão universitária em Anfíbios: Biologia, taxonomia e venenos, Instituto Butantan<p>
1998 - Legislação ambiental, IB-USP-Semana Temática<p>
1997 - Extensão universitária - Ecologia Vegetal, Instituto de Biociências da USP<p>
1997 - Extensão universitária - Aspectos da biologia, comportamento e conservação de répteis, Fundação Parque Zoológico de São Paulo<p>
1997 - Observação de aves, Centro de Estudos Ornitológicos<p>

<h3>Volunteer experience</h3>

- Vice-president of the International Association of Landscape Ecology - Brazilian Chapter (2010-Present)

- TEAR NGO (Tourism, Ecology and Artcraft from Ribeirão Grande, SP); organizing Agroforests and tree saplings symposiums for small land holders; participate in the "Rio Limpo" (clean river) project, with the main objective to raise awareness to the pollution in the Ribeirão Grande; site selection for restoration, with focus in the riparian areas, and restoration of these areas.

- Student representative in the International Association for Landscape Ecology - Brazilian Chapter (2005-2010)

- Student representative in the Department of Ecology, University of São Paulo (2000-2001)
 
<h3>Computer skills</h3>

R, MarkDown, HTML, ArcGIS, basic Python and SQL 

<h3>Outreach</h3>

GitHub <a href="https://github.com/alecamar"> alecamar</a>

<a href="https://www.researchgate.net/profile/Alexandre_Martensen"> Researchgate  </a>

<a href="https://utoronto.academia.edu/AlexandreMartensen"> Academia </a>

<a href="http://orcid.org/0000-0001-9017-7480"> orcid </a>

<a href="http://scholar.google.ca/citations?user=akY5N4EAAAAJ&hl=en"> Google Scholar </a>











